# ##### SUCCESS #####

# ##### ERROR #####
CODE_ERROR_INTERNAL_LIBRARY = "ERROR_INTERNAL_LIBRARY"
CODE_ERROR_BOOK_RETURN_REQUIRED = "ERROR_BOOK_RETURN_REQUIRED"
CODE_ERROR_OUT_OF_STOCK = "ERROR_OUT_OF_STOCK"

# ##### NOT_VALID #####
CODE_NOT_VALID_INTEGER = "NOT_VALID_INTEGER"
CODE_NOT_VALID_USER = "NOT_VALID_USER"
CODE_NOT_VALID_BOOK = "NOT_VALID_BOOK"

# ##### NOT_EXISTS #####

# ##### ALREADY_EXISTS #####
CODE_ALREADY_EXISTS_BOOK_RENTED = "ALREADY_EXISTS_BOOK_RENTED"
CODE_ALREADY_EXISTS_USER = "ALREADY_EXISTS_USER"

# ##### NOT_FOUND #####
CODE_NOT_FOUND_BOOK = "NOT_FOUND_BOOK"
CODE_NOT_FOUND_RENTED_BOOK = "NOT_FOUND_RENTED_BOOK"
CODE_NOT_FOUND_USER = "NOT_FOUND_USER"
